/*
 * Generated by scripts/build-art.mjs, which also bakes these blocks. Do not
 * edit by hand: change the script and run `node packages/kipos/scripts/build-art.mjs`.
 * Garden units, measured from the face's and the coping's top left.
 */

export type Stone = {
  variant: number
  left: number
  top: number
  width: number
  height: number
  /** Degrees off level. */
  tilt: number
  tone: number
  warm: number
  lichen: 0 | 1
  /** Where the lichen grows, in percent of the block. */
  lx: number
  ly: number
}

export type Capstone = { variant: number; left: number; width: number; tone: number }

export const STONES: Stone[] = [{"variant":5,"left":0,"top":0.3,"width":97.8,"height":48.2,"tilt":0.61,"tone":1.052,"warm":0.27,"lichen":0,"lx":29,"ly":59},{"variant":6,"left":103.8,"top":0.6,"width":130.8,"height":48.1,"tilt":-1.01,"tone":0.881,"warm":0.26,"lichen":0,"lx":52,"ly":75},{"variant":3,"left":240.7,"top":1,"width":89.2,"height":48,"tilt":0.6,"tone":0.942,"warm":0.09,"lichen":0,"lx":47,"ly":53},{"variant":7,"left":335.9,"top":0.9,"width":125.1,"height":46.2,"tilt":0.18,"tone":0.962,"warm":0.14,"lichen":1,"lx":45,"ly":71},{"variant":4,"left":467,"top":1.1,"width":99.7,"height":46,"tilt":-0.22,"tone":0.948,"warm":0.02,"lichen":1,"lx":48,"ly":59},{"variant":7,"left":577.8,"top":0.3,"width":147.5,"height":49.6,"tilt":-0.51,"tone":1.034,"warm":0.08,"lichen":1,"lx":15,"ly":65},{"variant":3,"left":731.2,"top":2.6,"width":93.3,"height":47.3,"tilt":-1.05,"tone":0.975,"warm":0.21,"lichen":0,"lx":4,"ly":85},{"variant":2,"left":836.9,"top":1.7,"width":70.4,"height":46.9,"tilt":1.1,"tone":0.943,"warm":0.15,"lichen":1,"lx":57,"ly":68},{"variant":1,"left":0,"top":54.5,"width":31.6,"height":44.5,"tilt":-0.8,"tone":0.979,"warm":0.17,"lichen":1,"lx":43,"ly":84},{"variant":2,"left":37.6,"top":56.6,"width":71.1,"height":42.5,"tilt":-0.3,"tone":0.936,"warm":0.17,"lichen":0,"lx":42,"ly":34},{"variant":7,"left":119.4,"top":54,"width":139.6,"height":45.9,"tilt":-0.57,"tone":0.956,"warm":0.04,"lichen":1,"lx":71,"ly":63},{"variant":6,"left":272.3,"top":55.2,"width":129.6,"height":43.9,"tilt":0.72,"tone":0.945,"warm":0.07,"lichen":0,"lx":65,"ly":40},{"variant":7,"left":407.9,"top":55.3,"width":154.8,"height":43.2,"tilt":0.61,"tone":1.057,"warm":0.07,"lichen":0,"lx":74,"ly":61},{"variant":8,"left":577,"top":54.2,"width":180.5,"height":45.7,"tilt":1.03,"tone":0.886,"warm":0.02,"lichen":0,"lx":3,"ly":84},{"variant":6,"left":763.5,"top":54.2,"width":140.3,"height":44.4,"tilt":0.75,"tone":0.985,"warm":0.24,"lichen":0,"lx":10,"ly":49}]

export const COPING: Capstone[] = [{"variant":3,"left":0,"width":177.2,"tone":0.98},{"variant":2,"left":181.2,"width":186.2,"tone":0.954},{"variant":0,"left":371.3,"width":149.8,"tone":1.03},{"variant":1,"left":525.1,"width":144.1,"tone":0.953},{"variant":2,"left":673.3,"width":168.6,"tone":0.986},{"variant":0,"left":845.9,"width":90.1,"tone":1.011}]
