/* Generated by scripts/generate-ornaments.mjs — edit the generator, not this file. */
import type { OrnamentLayout } from '../../components/layers.js'

export const ornament: OrnamentLayout = {
  placements: ['tl', 'tr', 'bl', 'br', 'top', 'bottom', 'left', 'right'],
  relief: { light: ['tl', 'tr', 'bl', 'br', 'top', 'bottom', 'left', 'right'] },
}
