/* Generated by scripts/generate-ornaments.mjs — edit the generator, not this file. */
import type { OrnamentLayout } from '../../components/layers.js'

export const ornament: OrnamentLayout = {
  placements: ['top', 'bottom', 'left', 'right', 'tl', 'tr', 'bl', 'br'],
  relief: { light: ['top', 'bottom', 'left', 'right', 'tl', 'tr', 'bl', 'br'], return: ['top', 'bottom', 'left', 'right', 'tl', 'tr', 'bl', 'br'] },
  micro: ['tl', 'tr', 'bl', 'br'],
}
