export { CraftTable } from './components/CraftTable.js'
export { GooglyEye, type GooglyEyeProps } from './components/GooglyEye.js'
export { bumpGooglyEyes } from './lib/bump.js'
export { PAPERS } from './lib/palette.js'
export { TABLE_HEIGHT, TABLE_WIDTH } from './lib/mat.js'
export { CraftPaper, type CraftPaperProps } from './components/CraftPaper.js'
export type { Edge } from './lib/tornEdge.js'
