export { CraftTable, type CraftTableProps } from './components/CraftTable.js'
export { defaultLabels, type CraftTableLabels } from './labels.js'
export { GooglyEye, type GooglyEyeProps } from './components/GooglyEye.js'
export { bumpGooglyEyes } from './lib/bump.js'
export { PAPERS } from './lib/palette.js'
export { CraftPaper, type CraftPaperProps } from './components/CraftPaper.js'
export type { Edge } from './lib/tornEdge.js'
