export { Vase, type VaseProps } from './components/Vase.js'
export { SHAPE_INFO as SHAPES, type ShapeId, type ShapeInfo } from './lib/shapes.js'
export { STYLES, type PaletteId, type StyleDef, type StyleId } from './lib/styles.js'
export type { IkarosPaletteId } from './lib/ikaros.js'
export type { GreekPaletteId } from './lib/greek.js'
